services:
  - type: web
    name: where-is-it
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
      - key: DOTNET_EnableDiagnostics
        value: "0"
